version: '3.1'
services:
  api:
    container_name: api
    restart: always
    build: 
      context: ./cryptotracker
    ports:
      - '8888:8888'
    depends_on:
      - db
  website:
    tty: true
    container_name: website
    restart: always
    build: 
      context: ./cryptotracker_website
    ports: 
      - '80:80'
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'cryptotracker'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'user' 
    ports:
      - '3310:3306'
    volumes:
      - "./cryptotracker-db:/var/lib/mysql"
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports: 
      - "9999:8080"